[book]
authors = ["114August514"]
language = "zh-CN"
src = "src"
title = "DiPECS 核心架构指南"

[output.html]
git-repository-url = "https://github.com/114August514/DiPECS"
edit-url-template = "https://github.com/114August514/DiPECS/edit/main/docs/{path}"
copy-fonts = true
mathjax-support = true
smart-punctuation = true
site-url = "/guide/"

[output.html.fold]
enable = true
level = 1

[output.html.search]
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
expand = true
heading-split-level = 2
copy-js = true

[preprocessor.graphviz]
command = "mdbook-graphviz"

